/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:62cb8d43-2b28-481e-b0eb-5815386d6ddb",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_SQuaTSjFi",
    "aws_user_pools_web_client_id": "3tfk7ai3iskq0n5jggrh66f7p3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://k7n7a7rr7rc6jakgq4du4okscu.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "evsdash-20210405140252-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "https://dmy4kyycl5fos.cloudfront.net"
};


export default awsmobile;
